# docker-compose.kafka.yml
version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
    - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      # ZOOKEEPER_CLIENT_PORT: 0.0.0.0:2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      #KAFKA_BROKER_ID: 1
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1


networks:
  default:
    external:
      name: kafka-network